/// The bank: every card the app can deal, and where it came from.
///
/// Cards are not code any more. They are JSON — one file per card under
/// `tool/cards/bank/`, written by the generator, read by whoever reviews
/// the pull request — and the app holds them two ways. A copy is baked in
/// at build time (`embedded_bank.dart`, generated by `tool/cards/bundle.py`)
/// so the first day works on a phone that has never been online. A newer
/// copy is downloaded as `cards.json` from the same site that serves the
/// web preview, kept in the phone's own storage, and adopted the next time
/// the app starts — never mid-day, so a deck already on the table is not
/// re-dealt under the reader.
///
/// The bank is a static, like the palette: the cards are the same for every
/// reader and every screen, and threading one object through forty widgets
/// to say so would be ceremony. What changes is *which* bundle is current,
/// and that changes in one place, [adopt].
library;

import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

import '../models/pill.dart';
import 'card_json.dart';
import 'embedded_bank.dart';

/// Where the newest bundle is published. The deploy workflow copies
/// `web/cards/` into the site, so this is a static file behind a CDN: no
/// server, no key, and a reader who is offline simply keeps what they have.
const String kBankUrl = 'https://lorenzballe.github.io/knowit/cards/cards.json';

/// What a fetch of [kBankUrl] returns: the body on 200, null on anything
/// else. Replaceable, so tests never touch the network.
typedef BankFetcher = Future<String?> Function(String url);

/// A parsed bundle: the cards, the calendar, and the stamp that orders it
/// against the one already in use.
class BankBundle {
  final int version;
  final String built;
  final List<Pill> cards;
  final Set<String> retired;
  final Map<int, String> editions;

  const BankBundle({
    required this.version,
    required this.built,
    required this.cards,
    required this.retired,
    required this.editions,
  });

  /// Reads a bundle. Throws [FormatException] on a document the app could
  /// not deal from, so a truncated download or a bad build is refused whole
  /// and the bank in use stays exactly as it was.
  factory BankBundle.parse(String text) {
    final Object? doc = jsonDecode(text);
    if (doc is! Map<String, Object?>) {
      throw const FormatException('a bundle is an object');
    }
    final version = doc['version'];
    if (version is! int) throw const FormatException('a bundle has a version');
    final rawCards = doc['cards'];
    if (rawCards is! List) throw const FormatException('a bundle has cards');
    final cards = <Pill>[];
    final retired = <String>{};
    final seen = <String>{};
    for (final raw in rawCards) {
      if (raw is! Map<String, Object?>) {
        throw const FormatException('a card is an object');
      }
      final card = cardFromJson(raw);
      if (!seen.add(card.id)) {
        throw FormatException('twice in the bundle', card.id);
      }
      cards.add(card);
      if (raw['disabled'] == true) retired.add(card.id);
    }
    if (cards.isEmpty) throw const FormatException('a bundle holds cards');
    final editions = <int, String>{};
    final rawEditions = doc['editions'];
    if (rawEditions is Map) {
      for (final e in rawEditions.entries) {
        final n = int.tryParse('${e.key}');
        final id = e.value;
        if (n == null || id is! String) {
          throw FormatException('edition ${e.key} is not a card');
        }
        if (!seen.contains(id)) {
          throw FormatException('edition $n names $id, which is not here');
        }
        editions[n] = id;
      }
    }
    return BankBundle(
      version: version,
      built: doc['built'] is String ? doc['built'] as String : '',
      cards: cards,
      retired: retired,
      editions: editions,
    );
  }
}

/// The bank in use.
class PillBank {
  const PillBank._();

  static const _kStored = 'knowit.bank';

  static BankBundle? _current;
  static Map<String, Pill>? _index;
  static List<Pill>? _dealable;

  /// The app's own copy, parsed once and kept: it is the floor the bank can
  /// never fall below.
  static final BankBundle embedded = BankBundle.parse(kEmbeddedBank);

  static BankBundle get _bundle => _current ??= embedded;

  /// Every card the dealer may put on the table today. A retired card stays
  /// in [byId] — a deck that was dealt yesterday still has to open — but is
  /// never dealt again.
  static List<Pill> get cards => _dealable ??= _bundle.retired.isEmpty
      ? List.unmodifiable(_bundle.cards)
      : List.unmodifiable(
          _bundle.cards.where((p) => !_bundle.retired.contains(p.id)),
        );

  /// The question of the day, by edition, as the bank froze it. Editions
  /// past the end of the calendar are dealt by the app itself.
  static Map<int, String> get editions => _bundle.editions;

  /// The stamp of the bundle in use; higher is newer.
  static int get version => _bundle.version;

  /// Where the bundle in use came from: the build, the last download, or
  /// nowhere yet.
  static String get built => _bundle.built;

  /// A card by id, retired or not.
  static Pill? byId(String id) =>
      (_index ??= {for (final p in _bundle.cards) p.id: p})[id];

  /// The bundle in use. The calendar keys its cache on this, so a swap
  /// re-deals the questions of the day from what the new bundle froze.
  static BankBundle get current => _bundle;

  /// Makes [bundle] the bank in use.
  static void adopt(BankBundle bundle) {
    _current = bundle;
    _index = null;
    _dealable = null;
  }

  /// Back to the copy the app shipped with. Tests, and nothing else.
  @visibleForTesting
  static void reset() => adopt(embedded);

  /// Adopts the bundle the last run downloaded, if it is newer than the
  /// one built in. Called once at start, before anything is dealt, and
  /// cheap when there is nothing stored.
  static void restore(SharedPreferences prefs) {
    final stored = prefs.getString(_kStored);
    if (stored == null) return;
    try {
      final bundle = BankBundle.parse(stored);
      if (bundle.version > embedded.version) adopt(bundle);
    } on FormatException {
      // A stored bundle the app can no longer read is worth less than the
      // one it shipped with. Forget it; the next fetch replaces it.
      prefs.remove(_kStored);
    }
  }

  /// How a bundle is fetched. Tests replace it; the default goes over HTTP.
  static BankFetcher fetch = _fetchOverHttp;

  /// Downloads the newest bundle and keeps it for the next start. Returns
  /// whether something newer than the bank in use was stored. Never throws:
  /// a phone with no signal is the normal case, not an error.
  static Future<bool> refresh(SharedPreferences prefs) async {
    try {
      final body = await fetch(kBankUrl);
      if (body == null) return false;
      final bundle = BankBundle.parse(body);
      if (bundle.version <= version) return false;
      await prefs.setString(_kStored, body);
      return true;
    } catch (error) {
      debugPrint('Astute: the bank did not refresh: $error');
      return false;
    }
  }

  static Future<String?> _fetchOverHttp(String url) async {
    final response = await http
        .get(Uri.parse(url))
        .timeout(const Duration(seconds: 20));
    if (response.statusCode != 200) return null;
    return utf8.decode(response.bodyBytes);
  }
}
