#!/usr/bin/env python3
"""Turns the bank into what the app reads.

    python3 tool/cards/bundle.py           # write both copies, extend the calendar
    python3 tool/cards/bundle.py --check   # fail if either copy is stale

The bank is one file per card, which is what a person reviews. The app
wants one document, twice: baked into the build as `lib/data/embedded_bank.dart`,
so the first day works offline, and published as `web/cards/cards.json`,
which the deploy copies to the site and every phone downloads. Both are
written here, from the same bytes, so they cannot disagree.

The calendar of questions of the day travels in the same document. It is
frozen — an edition, once written, never changes, whatever the pool does
afterwards — and this extends it a year past today so the app is never
without one. (Before the calendar existed the app computed it from the pool
on the fly, and a card added anywhere re-dealt every day since the epoch.)
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import random
import sys
from pathlib import Path

import check

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
EMBEDDED = ROOT / "lib" / "data" / "embedded_bank.dart"
PUBLISHED = ROOT / "web" / "cards" / "cards.json"

# Edition 1. The same date as kEpoch in lib/data/daily.dart.
EPOCH = dt.date(2026, 9, 1)
# How far ahead the calendar is kept.
AHEAD_DAYS = 400


def edition_of(day: dt.date) -> int:
    return (day - EPOCH).days + 1


def extend_editions(editions: dict[str, str], cards: list[dict], until: int) -> dict[str, str]:
    """Adds editions up to [until], keeping clear of what came before.

    A question stays out for three quarters of a lap of the graded pool, and
    never less than the gap check.py enforces; the pick is seeded by the
    edition so two machines extending the same calendar write the same thing.
    """
    graded = sorted(
        c["id"] for c in cards if c["kind"] in check.GRADED and not c.get("disabled")
    )
    if not graded:
        raise SystemExit("no graded card to make a question of the day from")
    window = max(check.EDITION_GAP, int(len(graded) * 0.75))
    out = dict(editions)
    last = max((int(k) for k in out), default=0)
    for e in range(last + 1, until + 1):
        recent = {out[str(x)] for x in range(e - window, e) if str(x) in out}
        fresh = [cid for cid in graded if cid not in recent]
        rng = random.Random(e * 7919 + 104729)
        out[str(e)] = rng.choice(fresh or graded)
    return out


def build(cards: list[dict], editions: dict[str, str], *, version: int, built: str) -> dict:
    return {
        "format": 1,
        "version": version,
        "built": built,
        "cards": [check.public(c) for c in cards],
        "editions": editions,
    }


def render_dart(text: str) -> str:
    if "'''" in text:
        raise SystemExit("a card contains three quotes in a row, which a Dart raw string cannot hold")
    return (
        "// GENERATED by tool/cards/bundle.py from tool/cards/bank/. Do not edit:\n"
        "// change a card in the bank and run the bundler. CI checks this is current.\n"
        "\n"
        "/// The bank the app ships with, as the JSON the site also serves.\n"
        "/// Parsed once, by PillBank.embedded.\n"
        "const String kEmbeddedBank = r'''\n"
        f"{text}"
        "''';\n"
    )


def same_content(a: dict | None, b: dict) -> bool:
    """Whether two bundles hold the same cards and calendar, whatever the stamp."""
    if a is None:
        return False
    return a.get("cards") == b.get("cards") and a.get("editions") == b.get("editions")


def read_embedded() -> dict | None:
    if not EMBEDDED.exists():
        return None
    text = EMBEDDED.read_text(encoding="utf-8")
    start, end = text.find("r'''\n"), text.rfind("''';")
    if start < 0 or end < 0:
        return None
    try:
        return json.loads(text[start + 5:end])
    except json.JSONDecodeError:
        return None


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="only report whether the copies are current")
    ap.add_argument("--today", help="YYYY-MM-DD, for a reproducible calendar (default: today)")
    args = ap.parse_args(argv)

    cards = check.load_bank()
    report = check.check_bank(cards)
    if report:
        for cid, problems in report.items():
            for p in problems:
                print(f"{cid}: {p}")
        print("the bank does not pass; nothing written")
        return 1

    today = dt.date.fromisoformat(args.today) if args.today else dt.date.today()
    editions = json.loads(check.EDITIONS.read_text(encoding="utf-8")) if check.EDITIONS.exists() else {}
    # A check holds the copies to the calendar as it is; only a write extends
    # it, or a bundle would go stale every midnight.
    if not args.check:
        editions = extend_editions(editions, cards, until=edition_of(today) + AHEAD_DAYS)
    problems = check.check_editions(editions, cards)
    if problems:
        for p in problems:
            print(p)
        return 1

    now = dt.datetime.now(dt.timezone.utc)
    bundle = build(cards, editions, version=int(now.strftime("%Y%m%d%H%M")), built=now.strftime("%Y-%m-%dT%H:%M:%SZ"))
    text = json.dumps(bundle, ensure_ascii=False, indent=1) + "\n"

    current = same_content(read_embedded(), bundle)
    published = PUBLISHED.exists() and same_content(json.loads(PUBLISHED.read_text(encoding="utf-8")), bundle)
    if args.check:
        if current and published:
            print(f"{len(cards)} cards, {len(editions)} editions: both copies current")
            return 0
        print("stale:" + ("" if current else " lib/data/embedded_bank.dart") + ("" if published else " web/cards/cards.json"))
        print("run python3 tool/cards/bundle.py")
        return 1

    if current and published:
        print(f"{len(cards)} cards, {len(editions)} editions: nothing to do")
        return 0
    check.EDITIONS.write_text(json.dumps(editions, indent=2) + "\n", encoding="utf-8")
    EMBEDDED.write_text(render_dart(text), encoding="utf-8")
    PUBLISHED.parent.mkdir(parents=True, exist_ok=True)
    PUBLISHED.write_text(text, encoding="utf-8")
    print(f"{len(cards)} cards, {len(editions)} editions, version {bundle['version']}")
    print(f"wrote {EMBEDDED.relative_to(ROOT)} and {PUBLISHED.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
